Repository falcosecurity/deploy-kubernetes, pull requests merged in 2022-06, with the labels that each got.

#1 docs(.github): add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: dco-signoff: yes, kind/update, lgtm, approved

#4 update(kubernetes): Deployment files
  kubernetes/falco/templates/clusterrole.yaml
  kubernetes/falco/templates/clusterrolebinding.yaml
  kubernetes/falco/templates/configmap.yaml
  kubernetes/falco/templates/daemonset.yaml
  kubernetes/falco/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, size/L

#5 update(kubernetes): Deployment files
  kubernetes/falco/templates/clusterrole.yaml
  kubernetes/falco/templates/clusterrolebinding.yaml
  kubernetes/falco/templates/configmap.yaml
  kubernetes/falco/templates/daemonset.yaml
  kubernetes/falco/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S

#6 update(kubernetes): Deployment files
  kubernetes/falco/templates/clusterrole.yaml
  kubernetes/falco/templates/clusterrolebinding.yaml
  kubernetes/falco/templates/configmap.yaml
  kubernetes/falco/templates/daemonset.yaml
  kubernetes/falco/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S

#7 update(kubernetes): Deployment files
  kubernetes/falco/templates/clusterrole.yaml
  kubernetes/falco/templates/clusterrolebinding.yaml
  kubernetes/falco/templates/configmap.yaml
  kubernetes/falco/templates/daemonset.yaml
  kubernetes/falco/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S

#8 update(kubernetes): Deployment files
  kubernetes/falcosidekick/templates/deployment.yaml
  kubernetes/falcosidekick/templates/rbac-ui.yaml
  kubernetes/falcosidekick/templates/rbac.yaml
  kubernetes/falcosidekick/templates/secrets.yaml
  kubernetes/falcosidekick/templates/service.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S

#10 docs(OWNERS): add zuc
  OWNERS
Labels: dco-signoff: yes, lgtm, approved, size/XS

#11 update: remove under development notice
  README.md
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS
