Repository falcosecurity/deploy-kubernetes, pull requests merged in 2023-06, with the labels that each got.

#69 update(README): add repo badges
  README.md
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#70 update(kubernetes): Deployment files
  kubernetes/falco/templates/clusterrole.yaml
  kubernetes/falco/templates/clusterrolebinding.yaml
  kubernetes/falco/templates/configmap.yaml
  kubernetes/falco/templates/daemonset.yaml
  kubernetes/falco/templates/falcoctl-configmap.yaml
  kubernetes/falco/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#71 update(kubernetes): Deployment files
  kubernetes/falco/templates/clusterrole.yaml
  kubernetes/falco/templates/clusterrolebinding.yaml
  kubernetes/falco/templates/configmap.yaml
  kubernetes/falco/templates/daemonset.yaml
  kubernetes/falco/templates/falcoctl-configmap.yaml
  kubernetes/falco/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S

#72 update(kubernetes): Deployment files
  kubernetes/falco/templates/clusterrole.yaml
  kubernetes/falco/templates/clusterrolebinding.yaml
  kubernetes/falco/templates/configmap.yaml
  kubernetes/falco/templates/daemonset.yaml
  kubernetes/falco/templates/falcoctl-configmap.yaml
  kubernetes/falco/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M
