Repository falcosecurity/deploy-kubernetes, pull requests merged in 2023-12, with the labels that each got.

#93 update(kubernetes): Deployment files
  kubernetes/falco/templates/clusterrole.yaml
  kubernetes/falco/templates/clusterrolebinding.yaml
  kubernetes/falco/templates/configmap.yaml
  kubernetes/falco/templates/daemonset.yaml
  kubernetes/falco/templates/falcoctl-configmap.yaml
  kubernetes/falco/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S

#94 update(kubernetes): Deployment files
  kubernetes/event-generator/templates/deployment.yaml
  kubernetes/event-generator/templates/rbac.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#96 update(docs): add more details to kubernetes readme
  kubernetes/README.md
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/M

#97 update(kubernetes): Deployment files
  kubernetes/falco/templates/clusterrole.yaml
  kubernetes/falco/templates/clusterrolebinding.yaml
  kubernetes/falco/templates/configmap.yaml
  kubernetes/falco/templates/daemonset.yaml
  kubernetes/falco/templates/falcoctl-configmap.yaml
  kubernetes/falco/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S

#98 update(kubernetes): Deployment files
  kubernetes/falcosidekick/templates/deployment.yaml
  kubernetes/falcosidekick/templates/rbac.yaml
  kubernetes/falcosidekick/templates/secrets.yaml
  kubernetes/falcosidekick/templates/service.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M
